#!/usr/bin/env ruby

require 'pry'

def dot_gitignore_paths
  Dir["*/.gitignore"]
end

def dot_gitignore_entries(dot_gitignore_path)
  folder_path = dot_gitignore_path.sub('/.gitignore', '')
  File.readlines(dot_gitignore_path)
  .reject {|e| e[0].eql?("\#")}
  .map {|e| [folder_path, e].join('/').gsub('//', '/') unless e.strip.empty? }
end

def add_gitignore_contents(f)
  dot_gitignore_paths.each do |dot_gitignore_path|
    folder_path = dot_gitignore_path.sub('/.gitignore', '')
    entries_str_ary = dot_gitignore_entries(dot_gitignore_path)
    f.write("\# entries from #{folder_path}")
    entries_str_ary.each {|e| f.write(e)}
  end



  # gitignore_files.each do |gf|
  #   path = File.path(gf).split
  #   contents_ary = File.readlines(gf)
  #   contents_ary.each do |line|
  #     updated_line = [path, line].join('/')
  #     f.write(updated_line)
  #   end
  # end
end

def refresh_main_gitignore
  f = File.new(".gitignore", 'w')
  f.write("\# compiled gitignore for all the projects\n")
  add_gitignore_contents(f)
  f.close
  g = File.read(".gitignore")
  puts g
end

refresh_main_gitignore
