#!/usr/bin/env ruby

require 'pry'

def dot_gitignore_paths
  Dir["*/.gitignore"]
end

def dot_gitignore_entries(dot_gitignore_path)
  folder_path = dot_gitignore_path.sub('/.gitignore', '')
  entries_str_ary = File.readlines(dot_gitignore_path)
  .reject {|e| e[0].eql?("\#")}
  .map {|e| [folder_path, e].join('/')}
end

def add_gitignore_contents(f)
  dot_gitignore_paths.each do |dot_gitignore_path|
    folder_path = dot_gitignore_path.sub('/.gitignore', '')
    entries_str_ary = dot_gitignore_entries(dot_gitignore_path)
    f.write("\n\# entries from #{folder_path}\n")
    entries_str_ary.each {|e| f.write(e)}
  end
end

def refresh_main_gitignore
  header = "\#\# COMPILED .gitignore FOR ALL THE projects\n"
  breakline = '## '
  (header.strip.length - 2).times { breakline += '-' }
  breakline += "\n"

  f = File.new(".gitignore", 'w')
  f.write(header)
  f.write(breakline)
  add_gitignore_contents(f)
  f.close
  g = File.read(".gitignore")
  puts g
end

refresh_main_gitignore
