source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"
gem "rails", "~> 7.0.1"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "brakeman"
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "capybara", "~> 3.35"
  gem "clipboard"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "guard-rubocop"
  gem "mocha"
  gem "pry-byebug"
  gem "rspec"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "rufo"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "watir-rails"
  gem "wisper-rspec"
end

group :development do
  gem "web-console"
  gem "guard"
  gem "guard-livereload"
  gem "guard-rspec"
end

group :test do
  gem "selenium-webdriver"
  gem "webdrivers"
end
