source 'https://rubygems.org'
gemspec

group :development do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'clipboard'
  gem 'did_you_mean'
  gem 'dotenv'
  gem 'guard', require: false
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'guard-shell'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'rainbow'
  gem 'rb-fsevent', '~> 0.9'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rspec', require: false
  gem 'rustici_software_cloud_v2', git: 'https://github.com/RusticiSoftware/scormcloud-api-v2-client-ruby'
  gem 'tty-box'
end
